# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0    

# See https://reuse.software/spec-3.2/#reusetoml for specification
version = 1

[[annotations]]
path = ["templates/**", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"