project_name: sparrow
builds:
  - env: [CGO_ENABLED=0]
    ldflags:
      - -s -w -X main.version={{ .Tag }}
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "ghcr.io/telekom/sparrow:latest"
      - "ghcr.io/telekom/sparrow:{{ .Tag }}"
      - "ghcr.io/telekom/sparrow:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/telekom/sparrow:v{{ .Major }}"
      - "mtr.devops.telekom.de/sparrow/sparrow:latest"
      - "mtr.devops.telekom.de/sparrow/sparrow:{{ .Tag }}"
      - "mtr.devops.telekom.de/sparrow/sparrow:v{{ .Major }}.{{ .Minor }}"
      - "mtr.devops.telekom.de/sparrow/sparrow:v{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://caas.telekom.de
      - --label=org.opencontainers.image.source=https://github.com/telekom/sparrow
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Timestamp }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="Apache 2.0"
nfpms:
  - maintainer: CaaS <opensource@telekom.de>
    description: |-
      Monitoring tool to gather infrastructure network information
    homepage: https://github.com/telekom
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk
