# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    ".idea/**",
    ".vscode/**",
    "**moq.go",
    "go.sum"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Deutsche Telekom IT GmbH"
SPDX-License-Identifier = "CC-BY-4.0"